_BASE_: "./Base-RCNN-C4.yaml"
OUTPUT_DIR: "output/test_vgg_city2fgcity"
INPUT:
  CROP:
    ENABLED: True

  MIN_SIZE_TRAIN: (600,)
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN_shortcut"
  BACKBONE:
    NAME: "build_vgg_backbone"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IN_FEATURES: ["vgg4"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 8
    IN_FEATURES: ["vgg4"]
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  WEIGHTS: "weights/vgg16_bn-6c64b313_converted_prefix.pth"
SOLVER:

  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (50000,)


  MAX_ITER: 60000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.04
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 1000
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_val","cityscapes_foggy_val")
SEMISUPNET:
  Trainer: "dinoteacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4"
  DIS_LOSS_WEIGHT: 0.0
  USE_FEATURE_ALIGN: False
  FEATURE_ALIGN_LOSS_TYPE: Cosine
  FEATURE_ALIGN_LAYER: "vgg4"
  ALIGN_MODEL: "dinov2_vitb14" 
  ALIGN_HEAD_TYPE: "MLP"
  ALIGN_HEAD_PROJ_DIM: 1024
  ALIGN_PROJ_GELU: False
  ALIGN_HEAD_NORMALIZE: True
  ALIGN_EASY_ONLY: True
  FEATURE_ALIGN_TARGET_START: 5000
  FEATURE_ALIGN_LOSS_WEIGHT: 1.0
  FEATURE_ALIGN_LOSS_WEIGHT_TARGET: 1.0 
  LABELER_TARGET_PSEUDOGT: None
  LABELER_PSEUDOGT_SWAP: False
  LABELER_PSEUDOGT_SWAP_ITER: 100000
  DINO_PATCH_SIZE: 14
  DINO_OUT_DIM: 768
  DOWNSTREAM_OUT_DIM: 512
  USE_ADV: False
  GC_CKPT_PATH: "output/dino_label/vit-B-gc/model_0034999.pth"
  CROSS_ALIGN: False
  CROSS_ALING_WEIGHT: 1.0
  CROSS_ALING_WEIGHT_TARGET: 1.0
  T_ADAPT: False
  T_ADAPT_PORJ_DIM: 256
  ALIGN_METHOD: "PIXEL"
  PSEUDO_KD: True
  ALBUM_AUG: False
  ALBUM_AUG_P: 0.5
TEST:
  EVAL_PERIOD: 5000


